apiVersion: apps/v1
kind: Deployment
metadata:
  name: api

spec:
  replicas: {{ .Values.api.replicaCount }}

  selector:
    matchLabels:
      app: api

  template:
    metadata:
      labels:
        app: api

    spec:
      containers:
        - name: api

          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"

          imagePullPolicy: {{ .Values.api.image.pullPolicy }}

          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: platform-app-config

            - secretRef:
                name: {{ .Values.secrets.existingSecret }}

          startupProbe:
            httpGet:
              path: /health
              port: 8000

            failureThreshold: 30
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /health
              port: 8000

            periodSeconds: 10
            timeoutSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 8000

            periodSeconds: 30
            timeoutSeconds: 5
