services:
  api:
    image: thanh2909/my-api:v0.1
    container_name: backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb
      - JWT_SECRET=change-me-please
      - JWT_EXPIRE_MINUTES=120
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET:-uploads}
      - AWS_S3_PUBLIC_URL=${AWS_S3_PUBLIC_URL:-http://localhost:9008/uploads}
      - AWS_S3_ENDPOINT_URL=http://minio:9000
      - AWS_S3_AUTO_CREATE_BUCKET=true
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-minioadmin}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-minioadmin}
    ports: ["8000:8000"]
    depends_on: [db, minio]
    networks:
      - appnet

  frontend:
    image: thanh2909/my-frontend:v0.1
    container_name: frontend
    environment:
      - API_BASE=http://localhost:8000
  

    ports: ["3000:80"]
    depends_on: [api]
    networks:
      - appnet

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - appnet

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID:-minioadmin}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY:-minioadmin}
    volumes:
      - minio_data:/data
    ports:
      - "9008:9000"
      - "9001:9001"
    networks:
      - appnet

volumes:
  db_data:
  minio_data:

networks:
  appnet:
    driver: bridge
