version: "3.11"
services:
  api:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb
      - JWT_SECRET=change-me-please
      - JWT_EXPIRE_MINUTES=120
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=uploads
      - MINIO_SECURE=false
      - MINIO_PUBLIC_URL=http://localhost:9000
    ports: ["8000:8000"]
    depends_on: [db, minio]

  frontend:
    build: ./frontend
    environment:
      - VITE_API_BASE=http://api:8000
    ports: ["3000:80"]
    depends_on: [api]

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

volumes:
  db_data:
  minio_data:
