services:
  api:
    image: thanh2909/simple-fullstack-docker-v3-ci-tests-api:v0.4
    #build: ./backend
    container_name: backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb
      - JWT_SECRET=change-me-please
      - JWT_EXPIRE_MINUTES=120
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=uploads
      - MINIO_SECURE=false
      - MINIO_PUBLIC_URL=http://localhost:9000
    ports: ["8000:8000"]
    depends_on: [db, minio]
    networks:
      - appnet

  frontend:
    image: thanh2909/simple-fullstack-docker-v3-ci-tests-frontend:v0.2
    #build: ./frontend
      
    container_name: frontend
    environment:
      - API_BASE=http://localhost:8000
  

    ports: ["3000:80"]
    depends_on: [api]
    networks:
      - appnet

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - appnet

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - appnet

volumes:
  db_data:
  minio_data:

networks:
  appnet:
    driver: bridge
