apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      annotations:
        checksum/config: {{ toJson .Values.frontend.env | sha256sum }}
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"

          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}

          ports:
            - containerPort: 80

          env:
            - name: API_BASE
              valueFrom:
                configMapKeyRef:
                  name: platform-app-config
                  key: API_BASE

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
